Feature/issue#10 create other requests
ASbeletsky/time-off-tracker-ui pull request #11
Opened 2020-11-01 11:02 UTC by DmytroKryvovychev

Реализована загрузка Других запросов для менеджеров, переделаны запросы на штатную апи, переделаны страницы Home, My Requests под нужды штатной апи, переработана страница Админа в связи с переходом на штатную апи.

2020-11-02 15:59 UTC, ASbeletsky requested changes

2020-11-02 15:59 UTC, ASbeletsky commented on src/components/OtherRequests/Approved.js
> +const types = [
похожий словарь был же еще и заявках - вынеси его тогда отдельно и заюзай тут

2020-11-02 15:59 UTC, ASbeletsky commented on src/components/OtherRequests/Approved.js
> +        array.push(5 * index);
наверно тут вместо 5 должно быть rowsPerPage, нет?

2020-11-02 15:59 UTC, ASbeletsky commented on src/components/OtherRequests/Approved.js
> +    }, '');
тут точно нельзя обойтись reviewsю.map(item => item.reviewer.firstName + item.reviewer.lastName).join(", ") ?

2020-11-02 15:59 UTC, ASbeletsky commented on src/components/OtherRequests/NewRequests.js
> +
много копипасты - вынеси все что выше отдельной и заюзай в NewRequests и в OtherRequests, в идеале это вообще должнен быть 1 компонент, только с разными настройками

2020-11-02 15:59 UTC, ASbeletsky commented on src/components/OtherRequests/Rejected.js
> +const testData = [
этого тут быть не должно)

2020-11-02 15:59 UTC, ASbeletsky commented on src/components/OtherRequests/Rejected.js
> +
опять же постарайся реюзнуть как компонент

2020-11-02 15:59 UTC, ASbeletsky commented on src/components/OtherRequests/ReviewsTable.js
> +
постарайся реюзнуть как компонент

2020-11-03 07:50 UTC, DmytroKryvovychev commented on src/components/OtherRequests/Approved.js
> +const types = [
Сделано. Файл constants.js

2020-11-03 07:59 UTC, DmytroKryvovychev commented on src/components/OtherRequests/Approved.js
> +        array.push(5 * index);
Тут всё нормально, сделано по документации аналогично Админ странице (тут работает как надо)

2020-11-03 08:02 UTC, DmytroKryvovychev commented on src/components/OtherRequests/Approved.js
> +    }, '');
Не вижу смысла такого делать доп. цикл, я выше делаю reduce, чтобы скомпоновать всех подписавших заявку в единую строку

2020-11-03 08:04 UTC, DmytroKryvovychev commented on src/components/OtherRequests/Rejected.js
> +const testData = [
Да:) Убрал

2020-11-03 08:33 UTC, DmytroKryvovychev commented on src/components/OtherRequests/Rejected.js
> +
Сделано.

2020-11-03 08:33 UTC, DmytroKryvovychev commented on src/components/OtherRequests/NewRequests.js
> +
Сделано.

2020-11-04 11:02 UTC, ASbeletsky commented on src/components/OtherRequests/Approved.js
> +    }, '');
Это называется преждевременная оптимизиция, но я не настаиваю)

2020-11-04 11:04 UTC, ASbeletsky approved these changes

2020-11-04 11:18 UTC, merged